name: kube-scheduler镜像推送

on:
  push:
    paths:
      - 'kube-scheduler/**'

jobs:
  build:

    runs-on: ubuntu-latest
    name: 编译 "${{matrix.podname}} ${{matrix.version}}"
    strategy:
      fail-fast: false
      matrix:
        include:
          - podname: kube-scheduler
            version: v1.29.4
            hub_name: xyz349925756
            
    steps:
      - name: 准备...
        uses: actions/checkout@v2

      - name: 登录 docker.io
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}

      - name: "构建"
        run: docker build . --file kube-scheduler/Dockerfile --tag ${{matrix.hub_name}}/${{matrix.podname}}:${{matrix.version}}
      
      - name: "上传"   
        run: docker push ${{matrix.hub_name}}/${{matrix.podname}}:${{matrix.version}} 