name: kube-scheduler-packages
  
on:
  push:
    paths:
      - 'kube-scheduler/**'

jobs:

  push:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
      
    strategy:
      fail-fast: false
      matrix:
        include:  
          - podname: kube-scheduler
            version: v1.29.4
    steps:
      - uses: actions/checkout@v2

      - name: Build image
        run: docker build . --file kube-scheduler/Dockerfile --tag ${{matrix.podname}}:${{matrix.version}}

      - name: Log in to registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Push image
        run: |
          docker tag ${{matrix.podname}}:${{matrix.version}} ghcr.io/${{ github.repository_owner }}/${{matrix.podname}}-${{matrix.version}}:${{matrix.version}}
          docker push ghcr.io/${{ github.repository_owner }}/${{matrix.podname}}-${{matrix.version}}:${{matrix.version}}